export interface CountryOption {
  code: string
  name: string
  flag: string
}

// Country mapping based on common MENA region + international markets
export const COUNTRY_MAPPING: Record<string, CountryOption> = {
  'AE': { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  'SA': { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  'EG': { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  'US': { code: 'US', name: 'United States', flag: '🇺🇸' },
  'GB': { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  'IN': { code: 'IN', name: 'India', flag: '🇮🇳' },
  'DE': { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  'FR': { code: 'FR', name: 'France', flag: '🇫🇷' },
  'CA': { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  'AU': { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  'SG': { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  'JP': { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  'CN': { code: 'CN', name: 'China', flag: '🇨🇳' },
  'BR': { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  'MX': { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  'KW': { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  'QA': { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  'BH': { code: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  'OM': { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  'JO': { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
  'LB': { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  'IL': { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  'TR': { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
  'PK': { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  'BD': { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  'PH': { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  'TH': { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  'MY': { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  'ID': { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  'VN': { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  'KR': { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  'IT': { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  'ES': { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  'NL': { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  'CH': { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  'SE': { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  'NO': { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  'DK': { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  'FI': { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  'IE': { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  'BE': { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  'AT': { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  'PT': { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  'GR': { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  'CZ': { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  'PL': { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  'HU': { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  'RO': { code: 'RO', name: 'Romania', flag: '🇷🇴' },
  'BG': { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  'HR': { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
  'SI': { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  'SK': { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  'LT': { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  'LV': { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  'EE': { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  'ZA': { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  'NG': { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  'KE': { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  'GH': { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  'MA': { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
  'TN': { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  'DZ': { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  'LY': { code: 'LY', name: 'Libya', flag: '🇱🇾' },
  'SD': { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  'ET': { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  'UG': { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  'TZ': { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  'RW': { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  'AR': { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  'CL': { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  'CO': { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  'PE': { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  'VE': { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  'UY': { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  'PY': { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  'BO': { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  'EC': { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  'CR': { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  'PA': { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  'GT': { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  'SV': { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  'HN': { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  'NI': { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  'DO': { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  'CU': { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  'JM': { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  'TT': { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  'BB': { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  'GD': { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  'LC': { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  'VC': { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  'AG': { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  'KN': { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  'DM': { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  'BS': { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  'BZ': { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  'GY': { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  'SR': { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  'GF': { code: 'GF', name: 'French Guiana', flag: '🇬🇫' },
  'FK': { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰' },
  'UZ': { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  'KZ': { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  'KG': { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  'TJ': { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯' },
  'TM': { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  'AF': { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  'IR': { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  'IQ': { code: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  'SY': { code: 'SY', name: 'Syria', flag: '🇸🇾' },
  'YE': { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  'PS': { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  'CY': { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  'MT': { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  'IS': { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
  'LU': { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  'LI': { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  'MC': { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  'SM': { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  'VA': { code: 'VA', name: 'Vatican City', flag: '🇻🇦' },
  'AD': { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  'RU': { code: 'RU', name: 'Russia', flag: '🇷🇺' },
  'UA': { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  'BY': { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  'MD': { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  'GE': { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  'AM': { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  'AZ': { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  'RS': { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  'ME': { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  'BA': { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  'MK': { code: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  'AL': { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  'XK': { code: 'XK', name: 'Kosovo', flag: '🇽🇰' },
  'NZ': { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  'FJ': { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  'PG': { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
  'SB': { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  'VU': { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  'NC': { code: 'NC', name: 'New Caledonia', flag: '🇳🇨' },
  'PF': { code: 'PF', name: 'French Polynesia', flag: '🇵🇫' },
  'WS': { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  'TO': { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  'KI': { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  'TV': { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  'NR': { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  'PW': { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  'FM': { code: 'FM', name: 'Micronesia', flag: '🇫🇲' },
  'MH': { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  'CK': { code: 'CK', name: 'Cook Islands', flag: '🇨🇰' },
  'NU': { code: 'NU', name: 'Niue', flag: '🇳🇺' },
  'TK': { code: 'TK', name: 'Tokelau', flag: '🇹🇰' },
  'WF': { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫' },
  'AS': { code: 'AS', name: 'American Samoa', flag: '🇦🇸' },
  'GU': { code: 'GU', name: 'Guam', flag: '🇬🇺' },
  'MP': { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵' },
  'VI': { code: 'VI', name: 'U.S. Virgin Islands', flag: '🇻🇮' },
  'PR': { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
}

export function getCountryOptions(): CountryOption[] {
  return Object.values(COUNTRY_MAPPING).sort((a, b) => a.name.localeCompare(b.name))
}

export function getCountryByCode(code: string): CountryOption | undefined {
  return COUNTRY_MAPPING[code]
}

export function formatCountryName(code: string): string {
  const country = getCountryByCode(code)
  return country ? country.name : code
}