// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqowwzdptapgdohkvjxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb3d3emRwdGFwZ2RvaGt2anhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjg1NDYsImV4cCI6MjA2MzkwNDU0Nn0.SZ0HvqLT6F8ghgxO355WZ1CJ1qYUBAYqzJoAe05HH-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);